# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.CharField(max_length=250)),
                ('Physician', models.CharField(max_length=250)),
                ('ResearcherID', models.IntegerField()),
                ('Hospital', models.CharField(max_length=250)),
                ('Cancer_Type', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='tevSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hugo_Symbol', models.CharField(max_length=150, null=True)),
                ('AA_Change', models.CharField(max_length=150, null=True)),
                ('allele', models.CharField(max_length=250, null=True)),
                ('Sample_Barcode', models.CharField(max_length=250, null=True)),
                ('alt_count', models.IntegerField(null=True)),
                ('ref_count', models.IntegerField(null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='data_input.patient')),
            ],
        ),
    ]
