# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tevSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hugo_Symbol', models.CharField(max_length=150)),
                ('AA_Change', models.CharField(max_length=150)),
                ('Sample_Barcode', models.CharField(max_length=250)),
                ('alt_count', models.IntegerField()),
                ('ref_count', models.IntegerField()),
            ],
        ),
    ]
