# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('hugo_symbol', models.CharField(max_length=250)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('timepoint', models.CharField(max_length=250)),
                ('timestamp', models.DateField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariantAllele',
            fields=[
                ('AA_position', models.IntegerField()),
                ('AA_original', models.CharField(max_length=10)),
                ('AA_variant', models.CharField(max_length=10)),
                ('alternative_freq', models.IntegerField()),
                ('reference_freq', models.IntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VariantAlleles', to='data_input.Gene')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VariantAlleles', to='data_input.Sample')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Samples', to='data_input.Source'),
        ),
    ]
