# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevsample',
            name='allele',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
