# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloneMetadata',
            fields=[
                ('key', models.CharField(max_length=250)),
                ('parent_index_of_this', models.CharField(max_length=10)),
                ('index', models.IntegerField()),
                ('group', models.IntegerField()),
                ('start_point', models.FloatField()),
                ('ploidy', models.IntegerField()),
                ('chrs_affected', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CloneTimepointData',
            fields=[
                ('Sample_Barcode', models.CharField(max_length=250)),
                ('alt_count', models.IntegerField()),
                ('allele', models.CharField(max_length=250)),
                ('cluster', models.IntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timepoint_data', to='data_manager.CloneMetadata')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('chromosome', models.CharField(max_length=2, null=True)),
                ('position', models.IntegerField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('timepoint', models.IntegerField()),
                ('sample_barcode', models.CharField(max_length=250, null=True)),
                ('assay', models.CharField(max_length=250, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SavedFishplotSubject',
            fields=[
                ('subject_id', models.CharField(max_length=250)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('subject_id', models.CharField(max_length=250)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariantAllele',
            fields=[
                ('AA_position', models.IntegerField()),
                ('AA_original', models.CharField(max_length=10)),
                ('AA_variant', models.CharField(max_length=10)),
                ('total_reads', models.IntegerField(null=True)),
                ('alt_reads', models.IntegerField(null=True)),
                ('ref_reads', models.IntegerField(null=True)),
                ('alternative', models.CharField(max_length=250, null=True)),
                ('alternative_freq', models.IntegerField()),
                ('reference', models.CharField(max_length=250)),
                ('reference_freq', models.IntegerField()),
                ('type', models.CharField(max_length=250, null=True)),
                ('cDNA_change', models.CharField(max_length=250, null=True)),
                ('ref_seq', models.CharField(max_length=250, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VariantAlleles', to='data_manager.Gene')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VariantAlleles', to='data_manager.Sample')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Samples', to='data_manager.Source'),
        ),
        migrations.AddField(
            model_name='name',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_as', to='data_manager.SavedFishplotSubject'),
        ),
        migrations.AddField(
            model_name='clonemetadata',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='data_manager.Name'),
        ),
        migrations.AddField(
            model_name='clonemetadata',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data_manager.CloneMetadata'),
        ),
    ]
