# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clonetimepointdata',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
    ]
