# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantallele',
            name='reference',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
